/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef SampleRegUC_H
#define SampleRegUC_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "SampleReg_Interface_UC_types.h"

namespace SampleReg {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class SampleRegUCIf {
 public:
  virtual ~SampleRegUCIf() {}

  /**
   * 向下位机发送心跳
   * @param timeStamp 时间戳（毫秒级）
   * 
   * @param timeStamp
   */
  virtual void HeartbeatToUC(const int64_t timeStamp) = 0;

  /**
   * 设备信息变更通知
   * @param info 变更后的设备信息
   * @return 0表示通知成功，非0表示错误码
   * 
   * @param info
   */
  virtual int32_t DeviceInfoChanged(const  ::SampleReg::DeviceInfo& info) = 0;

  /**
   * 任务信息变更通知
   * @param info 变更后的任务信息
   * @return 0表示通知成功，非0表示错误码
   * 
   * @param info
   */
  virtual int32_t TaskInfoChanged(const  ::SampleReg::TaskInfo& info) = 0;

  /**
   * 通用操作信息变更通知
   * @param info 变更后的通用操作信息
   * @return 0表示通知成功，非0表示错误码
   * 
   * @param info
   */
  virtual int32_t OperInfoChanged(const  ::SampleReg::GeneralOperInfo& info) = 0;
};

class SampleRegUCIfFactory {
 public:
  typedef SampleRegUCIf Handler;

  virtual ~SampleRegUCIfFactory() {}

  virtual SampleRegUCIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(SampleRegUCIf* /* handler */) = 0;
  };

class SampleRegUCIfSingletonFactory : virtual public SampleRegUCIfFactory {
 public:
  SampleRegUCIfSingletonFactory(const ::std::shared_ptr<SampleRegUCIf>& iface) : iface_(iface) {}
  virtual ~SampleRegUCIfSingletonFactory() {}

  virtual SampleRegUCIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(SampleRegUCIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<SampleRegUCIf> iface_;
};

class SampleRegUCNull : virtual public SampleRegUCIf {
 public:
  virtual ~SampleRegUCNull() {}
  void HeartbeatToUC(const int64_t /* timeStamp */) override {
    return;
  }
  int32_t DeviceInfoChanged(const  ::SampleReg::DeviceInfo& /* info */) override {
    int32_t _return = 0;
    return _return;
  }
  int32_t TaskInfoChanged(const  ::SampleReg::TaskInfo& /* info */) override {
    int32_t _return = 0;
    return _return;
  }
  int32_t OperInfoChanged(const  ::SampleReg::GeneralOperInfo& /* info */) override {
    int32_t _return = 0;
    return _return;
  }
};

typedef struct _SampleRegUC_HeartbeatToUC_args__isset {
  _SampleRegUC_HeartbeatToUC_args__isset() : timeStamp(false) {}
  bool timeStamp :1;
} _SampleRegUC_HeartbeatToUC_args__isset;

class SampleRegUC_HeartbeatToUC_args {
 public:

  SampleRegUC_HeartbeatToUC_args(const SampleRegUC_HeartbeatToUC_args&) noexcept;
  SampleRegUC_HeartbeatToUC_args& operator=(const SampleRegUC_HeartbeatToUC_args&) noexcept;
  SampleRegUC_HeartbeatToUC_args() noexcept
                                 : timeStamp(0) {
  }

  virtual ~SampleRegUC_HeartbeatToUC_args() noexcept;
  int64_t timeStamp;

  _SampleRegUC_HeartbeatToUC_args__isset __isset;

  void __set_timeStamp(const int64_t val);

  bool operator == (const SampleRegUC_HeartbeatToUC_args & rhs) const
  {
    if (!(timeStamp == rhs.timeStamp))
      return false;
    return true;
  }
  bool operator != (const SampleRegUC_HeartbeatToUC_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SampleRegUC_HeartbeatToUC_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class SampleRegUC_HeartbeatToUC_pargs {
 public:


  virtual ~SampleRegUC_HeartbeatToUC_pargs() noexcept;
  const int64_t* timeStamp;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class SampleRegUC_HeartbeatToUC_result {
 public:

  SampleRegUC_HeartbeatToUC_result(const SampleRegUC_HeartbeatToUC_result&) noexcept;
  SampleRegUC_HeartbeatToUC_result& operator=(const SampleRegUC_HeartbeatToUC_result&) noexcept;
  SampleRegUC_HeartbeatToUC_result() noexcept {
  }

  virtual ~SampleRegUC_HeartbeatToUC_result() noexcept;

  bool operator == (const SampleRegUC_HeartbeatToUC_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const SampleRegUC_HeartbeatToUC_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SampleRegUC_HeartbeatToUC_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class SampleRegUC_HeartbeatToUC_presult {
 public:


  virtual ~SampleRegUC_HeartbeatToUC_presult() noexcept;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _SampleRegUC_DeviceInfoChanged_args__isset {
  _SampleRegUC_DeviceInfoChanged_args__isset() : info(false) {}
  bool info :1;
} _SampleRegUC_DeviceInfoChanged_args__isset;

class SampleRegUC_DeviceInfoChanged_args {
 public:

  SampleRegUC_DeviceInfoChanged_args(const SampleRegUC_DeviceInfoChanged_args&) noexcept;
  SampleRegUC_DeviceInfoChanged_args& operator=(const SampleRegUC_DeviceInfoChanged_args&) noexcept;
  SampleRegUC_DeviceInfoChanged_args() noexcept {
  }

  virtual ~SampleRegUC_DeviceInfoChanged_args() noexcept;
   ::SampleReg::DeviceInfo info;

  _SampleRegUC_DeviceInfoChanged_args__isset __isset;

  void __set_info(const  ::SampleReg::DeviceInfo& val);

  bool operator == (const SampleRegUC_DeviceInfoChanged_args & rhs) const
  {
    if (!(info == rhs.info))
      return false;
    return true;
  }
  bool operator != (const SampleRegUC_DeviceInfoChanged_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SampleRegUC_DeviceInfoChanged_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class SampleRegUC_DeviceInfoChanged_pargs {
 public:


  virtual ~SampleRegUC_DeviceInfoChanged_pargs() noexcept;
  const  ::SampleReg::DeviceInfo* info;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SampleRegUC_DeviceInfoChanged_result__isset {
  _SampleRegUC_DeviceInfoChanged_result__isset() : success(false) {}
  bool success :1;
} _SampleRegUC_DeviceInfoChanged_result__isset;

class SampleRegUC_DeviceInfoChanged_result {
 public:

  SampleRegUC_DeviceInfoChanged_result(const SampleRegUC_DeviceInfoChanged_result&) noexcept;
  SampleRegUC_DeviceInfoChanged_result& operator=(const SampleRegUC_DeviceInfoChanged_result&) noexcept;
  SampleRegUC_DeviceInfoChanged_result() noexcept
                                       : success(0) {
  }

  virtual ~SampleRegUC_DeviceInfoChanged_result() noexcept;
  int32_t success;

  _SampleRegUC_DeviceInfoChanged_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const SampleRegUC_DeviceInfoChanged_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const SampleRegUC_DeviceInfoChanged_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SampleRegUC_DeviceInfoChanged_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SampleRegUC_DeviceInfoChanged_presult__isset {
  _SampleRegUC_DeviceInfoChanged_presult__isset() : success(false) {}
  bool success :1;
} _SampleRegUC_DeviceInfoChanged_presult__isset;

class SampleRegUC_DeviceInfoChanged_presult {
 public:


  virtual ~SampleRegUC_DeviceInfoChanged_presult() noexcept;
  int32_t* success;

  _SampleRegUC_DeviceInfoChanged_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _SampleRegUC_TaskInfoChanged_args__isset {
  _SampleRegUC_TaskInfoChanged_args__isset() : info(false) {}
  bool info :1;
} _SampleRegUC_TaskInfoChanged_args__isset;

class SampleRegUC_TaskInfoChanged_args {
 public:

  SampleRegUC_TaskInfoChanged_args(const SampleRegUC_TaskInfoChanged_args&);
  SampleRegUC_TaskInfoChanged_args& operator=(const SampleRegUC_TaskInfoChanged_args&);
  SampleRegUC_TaskInfoChanged_args() noexcept {
  }

  virtual ~SampleRegUC_TaskInfoChanged_args() noexcept;
   ::SampleReg::TaskInfo info;

  _SampleRegUC_TaskInfoChanged_args__isset __isset;

  void __set_info(const  ::SampleReg::TaskInfo& val);

  bool operator == (const SampleRegUC_TaskInfoChanged_args & rhs) const
  {
    if (!(info == rhs.info))
      return false;
    return true;
  }
  bool operator != (const SampleRegUC_TaskInfoChanged_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SampleRegUC_TaskInfoChanged_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class SampleRegUC_TaskInfoChanged_pargs {
 public:


  virtual ~SampleRegUC_TaskInfoChanged_pargs() noexcept;
  const  ::SampleReg::TaskInfo* info;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SampleRegUC_TaskInfoChanged_result__isset {
  _SampleRegUC_TaskInfoChanged_result__isset() : success(false) {}
  bool success :1;
} _SampleRegUC_TaskInfoChanged_result__isset;

class SampleRegUC_TaskInfoChanged_result {
 public:

  SampleRegUC_TaskInfoChanged_result(const SampleRegUC_TaskInfoChanged_result&) noexcept;
  SampleRegUC_TaskInfoChanged_result& operator=(const SampleRegUC_TaskInfoChanged_result&) noexcept;
  SampleRegUC_TaskInfoChanged_result() noexcept
                                     : success(0) {
  }

  virtual ~SampleRegUC_TaskInfoChanged_result() noexcept;
  int32_t success;

  _SampleRegUC_TaskInfoChanged_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const SampleRegUC_TaskInfoChanged_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const SampleRegUC_TaskInfoChanged_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SampleRegUC_TaskInfoChanged_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SampleRegUC_TaskInfoChanged_presult__isset {
  _SampleRegUC_TaskInfoChanged_presult__isset() : success(false) {}
  bool success :1;
} _SampleRegUC_TaskInfoChanged_presult__isset;

class SampleRegUC_TaskInfoChanged_presult {
 public:


  virtual ~SampleRegUC_TaskInfoChanged_presult() noexcept;
  int32_t* success;

  _SampleRegUC_TaskInfoChanged_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _SampleRegUC_OperInfoChanged_args__isset {
  _SampleRegUC_OperInfoChanged_args__isset() : info(false) {}
  bool info :1;
} _SampleRegUC_OperInfoChanged_args__isset;

class SampleRegUC_OperInfoChanged_args {
 public:

  SampleRegUC_OperInfoChanged_args(const SampleRegUC_OperInfoChanged_args&);
  SampleRegUC_OperInfoChanged_args& operator=(const SampleRegUC_OperInfoChanged_args&);
  SampleRegUC_OperInfoChanged_args() noexcept {
  }

  virtual ~SampleRegUC_OperInfoChanged_args() noexcept;
   ::SampleReg::GeneralOperInfo info;

  _SampleRegUC_OperInfoChanged_args__isset __isset;

  void __set_info(const  ::SampleReg::GeneralOperInfo& val);

  bool operator == (const SampleRegUC_OperInfoChanged_args & rhs) const
  {
    if (!(info == rhs.info))
      return false;
    return true;
  }
  bool operator != (const SampleRegUC_OperInfoChanged_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SampleRegUC_OperInfoChanged_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class SampleRegUC_OperInfoChanged_pargs {
 public:


  virtual ~SampleRegUC_OperInfoChanged_pargs() noexcept;
  const  ::SampleReg::GeneralOperInfo* info;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SampleRegUC_OperInfoChanged_result__isset {
  _SampleRegUC_OperInfoChanged_result__isset() : success(false) {}
  bool success :1;
} _SampleRegUC_OperInfoChanged_result__isset;

class SampleRegUC_OperInfoChanged_result {
 public:

  SampleRegUC_OperInfoChanged_result(const SampleRegUC_OperInfoChanged_result&) noexcept;
  SampleRegUC_OperInfoChanged_result& operator=(const SampleRegUC_OperInfoChanged_result&) noexcept;
  SampleRegUC_OperInfoChanged_result() noexcept
                                     : success(0) {
  }

  virtual ~SampleRegUC_OperInfoChanged_result() noexcept;
  int32_t success;

  _SampleRegUC_OperInfoChanged_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const SampleRegUC_OperInfoChanged_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const SampleRegUC_OperInfoChanged_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SampleRegUC_OperInfoChanged_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SampleRegUC_OperInfoChanged_presult__isset {
  _SampleRegUC_OperInfoChanged_presult__isset() : success(false) {}
  bool success :1;
} _SampleRegUC_OperInfoChanged_presult__isset;

class SampleRegUC_OperInfoChanged_presult {
 public:


  virtual ~SampleRegUC_OperInfoChanged_presult() noexcept;
  int32_t* success;

  _SampleRegUC_OperInfoChanged_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class SampleRegUCClient : virtual public SampleRegUCIf {
 public:
  SampleRegUCClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  SampleRegUCClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  /**
   * 向下位机发送心跳
   * @param timeStamp 时间戳（毫秒级）
   * 
   * @param timeStamp
   */
  void HeartbeatToUC(const int64_t timeStamp) override;
  void send_HeartbeatToUC(const int64_t timeStamp);
  void recv_HeartbeatToUC();
  /**
   * 设备信息变更通知
   * @param info 变更后的设备信息
   * @return 0表示通知成功，非0表示错误码
   * 
   * @param info
   */
  int32_t DeviceInfoChanged(const  ::SampleReg::DeviceInfo& info) override;
  void send_DeviceInfoChanged(const  ::SampleReg::DeviceInfo& info);
  int32_t recv_DeviceInfoChanged();
  /**
   * 任务信息变更通知
   * @param info 变更后的任务信息
   * @return 0表示通知成功，非0表示错误码
   * 
   * @param info
   */
  int32_t TaskInfoChanged(const  ::SampleReg::TaskInfo& info) override;
  void send_TaskInfoChanged(const  ::SampleReg::TaskInfo& info);
  int32_t recv_TaskInfoChanged();
  /**
   * 通用操作信息变更通知
   * @param info 变更后的通用操作信息
   * @return 0表示通知成功，非0表示错误码
   * 
   * @param info
   */
  int32_t OperInfoChanged(const  ::SampleReg::GeneralOperInfo& info) override;
  void send_OperInfoChanged(const  ::SampleReg::GeneralOperInfo& info);
  int32_t recv_OperInfoChanged();
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class SampleRegUCProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<SampleRegUCIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (SampleRegUCProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_HeartbeatToUC(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_DeviceInfoChanged(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_TaskInfoChanged(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_OperInfoChanged(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  SampleRegUCProcessor(::std::shared_ptr<SampleRegUCIf> iface) :
    iface_(iface) {
    processMap_["HeartbeatToUC"] = &SampleRegUCProcessor::process_HeartbeatToUC;
    processMap_["DeviceInfoChanged"] = &SampleRegUCProcessor::process_DeviceInfoChanged;
    processMap_["TaskInfoChanged"] = &SampleRegUCProcessor::process_TaskInfoChanged;
    processMap_["OperInfoChanged"] = &SampleRegUCProcessor::process_OperInfoChanged;
  }

  virtual ~SampleRegUCProcessor() {}
};

class SampleRegUCProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  SampleRegUCProcessorFactory(const ::std::shared_ptr< SampleRegUCIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< SampleRegUCIfFactory > handlerFactory_;
};

class SampleRegUCMultiface : virtual public SampleRegUCIf {
 public:
  SampleRegUCMultiface(std::vector<std::shared_ptr<SampleRegUCIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~SampleRegUCMultiface() {}
 protected:
  std::vector<std::shared_ptr<SampleRegUCIf> > ifaces_;
  SampleRegUCMultiface() {}
  void add(::std::shared_ptr<SampleRegUCIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  /**
   * 向下位机发送心跳
   * @param timeStamp 时间戳（毫秒级）
   * 
   * @param timeStamp
   */
  void HeartbeatToUC(const int64_t timeStamp) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->HeartbeatToUC(timeStamp);
    }
    ifaces_[i]->HeartbeatToUC(timeStamp);
  }

  /**
   * 设备信息变更通知
   * @param info 变更后的设备信息
   * @return 0表示通知成功，非0表示错误码
   * 
   * @param info
   */
  int32_t DeviceInfoChanged(const  ::SampleReg::DeviceInfo& info) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->DeviceInfoChanged(info);
    }
    return ifaces_[i]->DeviceInfoChanged(info);
  }

  /**
   * 任务信息变更通知
   * @param info 变更后的任务信息
   * @return 0表示通知成功，非0表示错误码
   * 
   * @param info
   */
  int32_t TaskInfoChanged(const  ::SampleReg::TaskInfo& info) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->TaskInfoChanged(info);
    }
    return ifaces_[i]->TaskInfoChanged(info);
  }

  /**
   * 通用操作信息变更通知
   * @param info 变更后的通用操作信息
   * @return 0表示通知成功，非0表示错误码
   * 
   * @param info
   */
  int32_t OperInfoChanged(const  ::SampleReg::GeneralOperInfo& info) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->OperInfoChanged(info);
    }
    return ifaces_[i]->OperInfoChanged(info);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class SampleRegUCConcurrentClient : virtual public SampleRegUCIf {
 public:
  SampleRegUCConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  SampleRegUCConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  /**
   * 向下位机发送心跳
   * @param timeStamp 时间戳（毫秒级）
   * 
   * @param timeStamp
   */
  void HeartbeatToUC(const int64_t timeStamp) override;
  int32_t send_HeartbeatToUC(const int64_t timeStamp);
  void recv_HeartbeatToUC(const int32_t seqid);
  /**
   * 设备信息变更通知
   * @param info 变更后的设备信息
   * @return 0表示通知成功，非0表示错误码
   * 
   * @param info
   */
  int32_t DeviceInfoChanged(const  ::SampleReg::DeviceInfo& info) override;
  int32_t send_DeviceInfoChanged(const  ::SampleReg::DeviceInfo& info);
  int32_t recv_DeviceInfoChanged(const int32_t seqid);
  /**
   * 任务信息变更通知
   * @param info 变更后的任务信息
   * @return 0表示通知成功，非0表示错误码
   * 
   * @param info
   */
  int32_t TaskInfoChanged(const  ::SampleReg::TaskInfo& info) override;
  int32_t send_TaskInfoChanged(const  ::SampleReg::TaskInfo& info);
  int32_t recv_TaskInfoChanged(const int32_t seqid);
  /**
   * 通用操作信息变更通知
   * @param info 变更后的通用操作信息
   * @return 0表示通知成功，非0表示错误码
   * 
   * @param info
   */
  int32_t OperInfoChanged(const  ::SampleReg::GeneralOperInfo& info) override;
  int32_t send_OperInfoChanged(const  ::SampleReg::GeneralOperInfo& info);
  int32_t recv_OperInfoChanged(const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
