/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef SampleReg_Defs_TYPES_H
#define SampleReg_Defs_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>


namespace SampleReg {

/**
 * 通用操作指令枚举
 * 用于上位机对下位机发起的控制指令
 */
struct GeneralOperCmd {
  enum type {
    Nothing = 0,
    ResetNetCfg = 1,
    ResetBaseCfg = 2,
    ResetCameraCfg = 3,
    ResetAllCfg = 4,
    UpgradeApp = 5,
    GetBaseInfo = 6,
    ExportLog = 7,
    GetCameraImage = 8,
    TimeSync = 9
  };
};

extern const std::map<int, const char*> _GeneralOperCmd_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const GeneralOperCmd::type& val);

std::string to_string(const GeneralOperCmd::type& val);

/**
 * 通用操作执行状态枚举
 * 用于标识操作的执行进度
 */
struct GeneralOperState {
  enum type {
    Nothing = 0,
    Issued = 1,
    Doing = 2,
    WaitReboot = 3,
    Finished = 4
  };
};

extern const std::map<int, const char*> _GeneralOperState_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const GeneralOperState::type& val);

std::string to_string(const GeneralOperState::type& val);

/**
 * 设备运行状态枚举
 */
struct RunningState {
  enum type {
    Ready = 0,
    Reseting = 1,
    Stop = 2,
    Fault = 3
  };
};

extern const std::map<int, const char*> _RunningState_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const RunningState::type& val);

std::string to_string(const RunningState::type& val);

/**
 * 样本管管帽颜色枚举
 */
struct TubeHatColor {
  enum type {
    TUBE_HAT_RED = 0,
    TUBE_HAT_PINK = 1,
    TUBE_HAT_BLUE = 2,
    TUBE_HAT_BLACK = 3,
    TUBE_HAT_GREEN = 4,
    TUBE_HAT_PURPLE = 5,
    TUBE_HAT_GRAY = 6,
    TUBE_HAT_ORANGE = 7,
    TUBE_HAT_YELLOW = 8,
    TUBE_HAT_WHITE = 9,
    TUBE_HAT_UNKNOWN = 10,
    TUBE_HAT_NONE = 11
  };
};

extern const std::map<int, const char*> _TubeHatColor_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TubeHatColor::type& val);

std::string to_string(const TubeHatColor::type& val);

/**
 * 试管类型枚举
 */
struct TubeType {
  enum type {
    HITACHI_MICRO_TUBE = 0,
    UNKNOWN_TUBE = 1,
    QUALITY_CONTROL_TUBE = 2,
    HITACHI_STANDARD_TUBE = 3,
    BLOOD_COLLECTION_TUBE = 4,
    BLANK = 5
  };
};

extern const std::map<int, const char*> _TubeType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TubeType::type& val);

std::string to_string(const TubeType::type& val);

/**
 * 俯拍试管状态枚举
 */
struct TubeOverHeadStatus {
  enum type {
    UNKNOWN = -1,
    NO_TUBE = 0,
    NOHAT_TUBE = 1,
    HAT_TUBE = 2
  };
};

extern const std::map<int, const char*> _TubeOverHeadStatus_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TubeOverHeadStatus::type& val);

std::string to_string(const TubeOverHeadStatus::type& val);

/**
 * 管帽类型
 */
struct HatType {
  enum type {
    ONE_TIME_USE = 0,
    NORMAL = 1,
    NONE_HAT = 2
  };
};

extern const std::map<int, const char*> _HatType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const HatType::type& val);

std::string to_string(const HatType::type& val);

/**
 * 任务类型枚举
 * 对应视觉识别的具体功能
 */
struct TaskType {
  enum type {
    TASK_GET_BARCODE = 0,
    TASK_GET_BEST_BARCODE_IMAGE = 1,
    TASK_GET_BEST_LIQUID_IMAGE = 2,
    TASK_GET_TUBE_HEIGHT = 3,
    TASK_GET_TUBE_WIDTH = 4,
    TASK_GET_TUBE_EXIST = 5,
    TASK_GET_TUBE_HAT_COLOR = 6,
    TASK_GET_TUBE_TYPE = 7,
    TASK_GET_HAT_TYPE = 8,
    TASK_GET_TUBE_TILT = 9,
    TASK_GET_SERUM_INDEX = 10,
    TASK_GET_SAMPLE_SIZE = 11,
    TASK_GET_SAMPLE_CENTRIFUGED = 12,
    TASK_GET_SAMPLE_CENTRIFUGED_QUALITY = 13,
    TASK_GET_TUBE_OVERHEAD_AXIS = 14,
    TASK_GET_TUBE_OVERHEAD = 15,
    TASK_GET_TUBE_OVERHEAD_COLOR = 16
  };
};

extern const std::map<int, const char*> _TaskType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TaskType::type& val);

std::string to_string(const TaskType::type& val);

/**
 * 任务执行状态枚举
 */
struct TaskState {
  enum type {
    Nothing = 0,
    Issued = 1,
    Identifying = 2,
    Finished = 3
  };
};

extern const std::map<int, const char*> _TaskState_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TaskState::type& val);

std::string to_string(const TaskState::type& val);

class BaseInfo;

class ImageInfo;

class GeneralOperInfo;

class DeviceInfo;

class Bbox;

class TubeHatHSV;

class BarcodeInfo;

class BestBarcodeImageInfo;

class BestLiquidImageInfo;

class TubeHeightInfo;

class TubeWidthInfo;

class TubeExistInfo;

class TubeHatColorInfo;

class TubeTypeInfo;

class HatTypeInfo;

class TubeTiltInfo;

class SerumIndexInfo;

class SampleHeight;

class SampleVolume;

class SampleSizeInfo;

class SampleCentrifugedInfo;

class SampleCentrifugedQualityInfo;

class TubeOverHeadAxisInfo;

class TubeOverHeadInfo;

class TubeOverHeadColor;

class TaskResult;

class TaskInfo;

typedef struct _BaseInfo__isset {
  _BaseInfo__isset() : modVersion(false), algVersion(false), modID(false) {}
  bool modVersion :1;
  bool algVersion :1;
  bool modID :1;
} _BaseInfo__isset;

/**
 * 模块基础信息
 */
class BaseInfo : public virtual ::apache::thrift::TBase {
 public:

  BaseInfo(const BaseInfo&);
  BaseInfo& operator=(const BaseInfo&);
  BaseInfo() noexcept
           : modVersion(),
             algVersion(),
             modID() {
  }

  virtual ~BaseInfo() noexcept;
  std::string modVersion;
  std::string algVersion;
  std::string modID;

  _BaseInfo__isset __isset;

  void __set_modVersion(const std::string& val);

  void __set_algVersion(const std::string& val);

  void __set_modID(const std::string& val);

  bool operator == (const BaseInfo & rhs) const
  {
    if (!(modVersion == rhs.modVersion))
      return false;
    if (__isset.algVersion != rhs.__isset.algVersion)
      return false;
    else if (__isset.algVersion && !(algVersion == rhs.algVersion))
      return false;
    if (__isset.modID != rhs.__isset.modID)
      return false;
    else if (__isset.modID && !(modID == rhs.modID))
      return false;
    return true;
  }
  bool operator != (const BaseInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BaseInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(BaseInfo &a, BaseInfo &b);

std::ostream& operator<<(std::ostream& out, const BaseInfo& obj);

typedef struct _ImageInfo__isset {
  _ImageInfo__isset() : width(false), height(false), data(false) {}
  bool width :1;
  bool height :1;
  bool data :1;
} _ImageInfo__isset;

/**
 * GBR图像信息
 */
class ImageInfo : public virtual ::apache::thrift::TBase {
 public:

  ImageInfo(const ImageInfo&);
  ImageInfo& operator=(const ImageInfo&);
  ImageInfo() noexcept
            : width(0),
              height(0),
              data() {
  }

  virtual ~ImageInfo() noexcept;
  int32_t width;
  int32_t height;
  std::string data;

  _ImageInfo__isset __isset;

  void __set_width(const int32_t val);

  void __set_height(const int32_t val);

  void __set_data(const std::string& val);

  bool operator == (const ImageInfo & rhs) const
  {
    if (!(width == rhs.width))
      return false;
    if (!(height == rhs.height))
      return false;
    if (!(data == rhs.data))
      return false;
    return true;
  }
  bool operator != (const ImageInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ImageInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ImageInfo &a, ImageInfo &b);

std::ostream& operator<<(std::ostream& out, const ImageInfo& obj);

typedef struct _GeneralOperInfo__isset {
  _GeneralOperInfo__isset() : cmd(false), netCfgFile(false), baseCfgFile(false), cameraCfgFile(false), upgradePack(false), baseInfo(false), modLog(false), image(false), time(false), state(true), retCode(false) {}
  bool cmd :1;
  bool netCfgFile :1;
  bool baseCfgFile :1;
  bool cameraCfgFile :1;
  bool upgradePack :1;
  bool baseInfo :1;
  bool modLog :1;
  bool image :1;
  bool time :1;
  bool state :1;
  bool retCode :1;
} _GeneralOperInfo__isset;

/**
 * 通用操作信息结构体
 * 用于上位机下发操作指令及下位机返回执行结果
 */
class GeneralOperInfo : public virtual ::apache::thrift::TBase {
 public:

  GeneralOperInfo(const GeneralOperInfo&);
  GeneralOperInfo& operator=(const GeneralOperInfo&);
  GeneralOperInfo() noexcept
                  : cmd(static_cast<GeneralOperCmd::type>(0)),
                    netCfgFile(),
                    baseCfgFile(),
                    cameraCfgFile(),
                    upgradePack(),
                    modLog(),
                    time(),
                    state((GeneralOperState::type)0),
                    retCode(0) {
    state = (GeneralOperState::type)0;

  }

  virtual ~GeneralOperInfo() noexcept;
  /**
   * 
   * @see GeneralOperCmd
   */
  GeneralOperCmd::type cmd;
  std::string netCfgFile;
  std::string baseCfgFile;
  std::string cameraCfgFile;
  std::string upgradePack;
  BaseInfo baseInfo;
  std::string modLog;
  ImageInfo image;
  std::string time;
  /**
   * 
   * @see GeneralOperState
   */
  GeneralOperState::type state;
  int32_t retCode;

  _GeneralOperInfo__isset __isset;

  void __set_cmd(const GeneralOperCmd::type val);

  void __set_netCfgFile(const std::string& val);

  void __set_baseCfgFile(const std::string& val);

  void __set_cameraCfgFile(const std::string& val);

  void __set_upgradePack(const std::string& val);

  void __set_baseInfo(const BaseInfo& val);

  void __set_modLog(const std::string& val);

  void __set_image(const ImageInfo& val);

  void __set_time(const std::string& val);

  void __set_state(const GeneralOperState::type val);

  void __set_retCode(const int32_t val);

  bool operator == (const GeneralOperInfo & rhs) const
  {
    if (!(cmd == rhs.cmd))
      return false;
    if (__isset.netCfgFile != rhs.__isset.netCfgFile)
      return false;
    else if (__isset.netCfgFile && !(netCfgFile == rhs.netCfgFile))
      return false;
    if (__isset.baseCfgFile != rhs.__isset.baseCfgFile)
      return false;
    else if (__isset.baseCfgFile && !(baseCfgFile == rhs.baseCfgFile))
      return false;
    if (__isset.cameraCfgFile != rhs.__isset.cameraCfgFile)
      return false;
    else if (__isset.cameraCfgFile && !(cameraCfgFile == rhs.cameraCfgFile))
      return false;
    if (__isset.upgradePack != rhs.__isset.upgradePack)
      return false;
    else if (__isset.upgradePack && !(upgradePack == rhs.upgradePack))
      return false;
    if (__isset.baseInfo != rhs.__isset.baseInfo)
      return false;
    else if (__isset.baseInfo && !(baseInfo == rhs.baseInfo))
      return false;
    if (__isset.modLog != rhs.__isset.modLog)
      return false;
    else if (__isset.modLog && !(modLog == rhs.modLog))
      return false;
    if (__isset.image != rhs.__isset.image)
      return false;
    else if (__isset.image && !(image == rhs.image))
      return false;
    if (__isset.time != rhs.__isset.time)
      return false;
    else if (__isset.time && !(time == rhs.time))
      return false;
    if (!(state == rhs.state))
      return false;
    if (__isset.retCode != rhs.__isset.retCode)
      return false;
    else if (__isset.retCode && !(retCode == rhs.retCode))
      return false;
    return true;
  }
  bool operator != (const GeneralOperInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const GeneralOperInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(GeneralOperInfo &a, GeneralOperInfo &b);

std::ostream& operator<<(std::ostream& out, const GeneralOperInfo& obj);

typedef struct _DeviceInfo__isset {
  _DeviceInfo__isset() : runningState(false) {}
  bool runningState :1;
} _DeviceInfo__isset;

/**
 * 设备信息结构体
 * 包含设备当前的运行状态
 */
class DeviceInfo : public virtual ::apache::thrift::TBase {
 public:

  DeviceInfo(const DeviceInfo&) noexcept;
  DeviceInfo& operator=(const DeviceInfo&) noexcept;
  DeviceInfo() noexcept
             : runningState(static_cast<RunningState::type>(0)) {
  }

  virtual ~DeviceInfo() noexcept;
  /**
   * 
   * @see RunningState
   */
  RunningState::type runningState;

  _DeviceInfo__isset __isset;

  void __set_runningState(const RunningState::type val);

  bool operator == (const DeviceInfo & rhs) const
  {
    if (!(runningState == rhs.runningState))
      return false;
    return true;
  }
  bool operator != (const DeviceInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DeviceInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(DeviceInfo &a, DeviceInfo &b);

std::ostream& operator<<(std::ostream& out, const DeviceInfo& obj);

typedef struct _Bbox__isset {
  _Bbox__isset() : x(false), y(false), w(false), h(false) {}
  bool x :1;
  bool y :1;
  bool w :1;
  bool h :1;
} _Bbox__isset;

/**
 * 二维坐标矩形框结构体
 */
class Bbox : public virtual ::apache::thrift::TBase {
 public:

  Bbox(const Bbox&) noexcept;
  Bbox& operator=(const Bbox&) noexcept;
  Bbox() noexcept
       : x(0),
         y(0),
         w(0),
         h(0) {
  }

  virtual ~Bbox() noexcept;
  int32_t x;
  int32_t y;
  int32_t w;
  int32_t h;

  _Bbox__isset __isset;

  void __set_x(const int32_t val);

  void __set_y(const int32_t val);

  void __set_w(const int32_t val);

  void __set_h(const int32_t val);

  bool operator == (const Bbox & rhs) const
  {
    if (!(x == rhs.x))
      return false;
    if (!(y == rhs.y))
      return false;
    if (!(w == rhs.w))
      return false;
    if (!(h == rhs.h))
      return false;
    return true;
  }
  bool operator != (const Bbox &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Bbox & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(Bbox &a, Bbox &b);

std::ostream& operator<<(std::ostream& out, const Bbox& obj);

typedef struct _TubeHatHSV__isset {
  _TubeHatHSV__isset() : H(false), S(false), V(false) {}
  bool H :1;
  bool S :1;
  bool V :1;
} _TubeHatHSV__isset;

/**
 * 样本管管帽颜色HSV值结构体
 */
class TubeHatHSV : public virtual ::apache::thrift::TBase {
 public:

  TubeHatHSV(const TubeHatHSV&) noexcept;
  TubeHatHSV& operator=(const TubeHatHSV&) noexcept;
  TubeHatHSV() noexcept
             : H(0),
               S(0),
               V(0) {
  }

  virtual ~TubeHatHSV() noexcept;
  int8_t H;
  int8_t S;
  int8_t V;

  _TubeHatHSV__isset __isset;

  void __set_H(const int8_t val);

  void __set_S(const int8_t val);

  void __set_V(const int8_t val);

  bool operator == (const TubeHatHSV & rhs) const
  {
    if (!(H == rhs.H))
      return false;
    if (!(S == rhs.S))
      return false;
    if (!(V == rhs.V))
      return false;
    return true;
  }
  bool operator != (const TubeHatHSV &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TubeHatHSV & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TubeHatHSV &a, TubeHatHSV &b);

std::ostream& operator<<(std::ostream& out, const TubeHatHSV& obj);

typedef struct _BarcodeInfo__isset {
  _BarcodeInfo__isset() : barcodes(false), status(true) {}
  bool barcodes :1;
  bool status :1;
} _BarcodeInfo__isset;

/**
 * 条码信息结构体
 */
class BarcodeInfo : public virtual ::apache::thrift::TBase {
 public:

  BarcodeInfo(const BarcodeInfo&);
  BarcodeInfo& operator=(const BarcodeInfo&);
  BarcodeInfo() noexcept
              : status(-1) {
  }

  virtual ~BarcodeInfo() noexcept;
  std::vector<std::string>  barcodes;
  int32_t status;

  _BarcodeInfo__isset __isset;

  void __set_barcodes(const std::vector<std::string> & val);

  void __set_status(const int32_t val);

  bool operator == (const BarcodeInfo & rhs) const
  {
    if (__isset.barcodes != rhs.__isset.barcodes)
      return false;
    else if (__isset.barcodes && !(barcodes == rhs.barcodes))
      return false;
    if (!(status == rhs.status))
      return false;
    return true;
  }
  bool operator != (const BarcodeInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BarcodeInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(BarcodeInfo &a, BarcodeInfo &b);

std::ostream& operator<<(std::ostream& out, const BarcodeInfo& obj);

typedef struct _BestBarcodeImageInfo__isset {
  _BestBarcodeImageInfo__isset() : bestBarcodeImage(false), status(true) {}
  bool bestBarcodeImage :1;
  bool status :1;
} _BestBarcodeImageInfo__isset;

/**
 * 最佳条码图像信息结构体
 */
class BestBarcodeImageInfo : public virtual ::apache::thrift::TBase {
 public:

  BestBarcodeImageInfo(const BestBarcodeImageInfo&);
  BestBarcodeImageInfo& operator=(const BestBarcodeImageInfo&);
  BestBarcodeImageInfo() noexcept
                       : status(-1) {
  }

  virtual ~BestBarcodeImageInfo() noexcept;
  ImageInfo bestBarcodeImage;
  int32_t status;

  _BestBarcodeImageInfo__isset __isset;

  void __set_bestBarcodeImage(const ImageInfo& val);

  void __set_status(const int32_t val);

  bool operator == (const BestBarcodeImageInfo & rhs) const
  {
    if (__isset.bestBarcodeImage != rhs.__isset.bestBarcodeImage)
      return false;
    else if (__isset.bestBarcodeImage && !(bestBarcodeImage == rhs.bestBarcodeImage))
      return false;
    if (!(status == rhs.status))
      return false;
    return true;
  }
  bool operator != (const BestBarcodeImageInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BestBarcodeImageInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(BestBarcodeImageInfo &a, BestBarcodeImageInfo &b);

std::ostream& operator<<(std::ostream& out, const BestBarcodeImageInfo& obj);

typedef struct _BestLiquidImageInfo__isset {
  _BestLiquidImageInfo__isset() : bestLiquidImage(false), status(true) {}
  bool bestLiquidImage :1;
  bool status :1;
} _BestLiquidImageInfo__isset;

/**
 * 最佳液面图像信息结构体
 */
class BestLiquidImageInfo : public virtual ::apache::thrift::TBase {
 public:

  BestLiquidImageInfo(const BestLiquidImageInfo&);
  BestLiquidImageInfo& operator=(const BestLiquidImageInfo&);
  BestLiquidImageInfo() noexcept
                      : status(-1) {
  }

  virtual ~BestLiquidImageInfo() noexcept;
  ImageInfo bestLiquidImage;
  int32_t status;

  _BestLiquidImageInfo__isset __isset;

  void __set_bestLiquidImage(const ImageInfo& val);

  void __set_status(const int32_t val);

  bool operator == (const BestLiquidImageInfo & rhs) const
  {
    if (__isset.bestLiquidImage != rhs.__isset.bestLiquidImage)
      return false;
    else if (__isset.bestLiquidImage && !(bestLiquidImage == rhs.bestLiquidImage))
      return false;
    if (!(status == rhs.status))
      return false;
    return true;
  }
  bool operator != (const BestLiquidImageInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BestLiquidImageInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(BestLiquidImageInfo &a, BestLiquidImageInfo &b);

std::ostream& operator<<(std::ostream& out, const BestLiquidImageInfo& obj);

typedef struct _TubeHeightInfo__isset {
  _TubeHeightInfo__isset() : height(false), suspectHeight(false), status(true) {}
  bool height :1;
  bool suspectHeight :1;
  bool status :1;
} _TubeHeightInfo__isset;

/**
 * 试管高度信息结构体
 */
class TubeHeightInfo : public virtual ::apache::thrift::TBase {
 public:

  TubeHeightInfo(const TubeHeightInfo&) noexcept;
  TubeHeightInfo& operator=(const TubeHeightInfo&) noexcept;
  TubeHeightInfo() noexcept
                 : height(0),
                   suspectHeight(0),
                   status(-1) {
  }

  virtual ~TubeHeightInfo() noexcept;
  double height;
  int32_t suspectHeight;
  int32_t status;

  _TubeHeightInfo__isset __isset;

  void __set_height(const double val);

  void __set_suspectHeight(const int32_t val);

  void __set_status(const int32_t val);

  bool operator == (const TubeHeightInfo & rhs) const
  {
    if (__isset.height != rhs.__isset.height)
      return false;
    else if (__isset.height && !(height == rhs.height))
      return false;
    if (__isset.suspectHeight != rhs.__isset.suspectHeight)
      return false;
    else if (__isset.suspectHeight && !(suspectHeight == rhs.suspectHeight))
      return false;
    if (!(status == rhs.status))
      return false;
    return true;
  }
  bool operator != (const TubeHeightInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TubeHeightInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TubeHeightInfo &a, TubeHeightInfo &b);

std::ostream& operator<<(std::ostream& out, const TubeHeightInfo& obj);

typedef struct _TubeWidthInfo__isset {
  _TubeWidthInfo__isset() : width(false), suspectWidth(false), status(true) {}
  bool width :1;
  bool suspectWidth :1;
  bool status :1;
} _TubeWidthInfo__isset;

/**
 * 试管宽度信息结构体
 */
class TubeWidthInfo : public virtual ::apache::thrift::TBase {
 public:

  TubeWidthInfo(const TubeWidthInfo&) noexcept;
  TubeWidthInfo& operator=(const TubeWidthInfo&) noexcept;
  TubeWidthInfo() noexcept
                : width(0),
                  suspectWidth(0),
                  status(-1) {
  }

  virtual ~TubeWidthInfo() noexcept;
  double width;
  int32_t suspectWidth;
  int32_t status;

  _TubeWidthInfo__isset __isset;

  void __set_width(const double val);

  void __set_suspectWidth(const int32_t val);

  void __set_status(const int32_t val);

  bool operator == (const TubeWidthInfo & rhs) const
  {
    if (__isset.width != rhs.__isset.width)
      return false;
    else if (__isset.width && !(width == rhs.width))
      return false;
    if (__isset.suspectWidth != rhs.__isset.suspectWidth)
      return false;
    else if (__isset.suspectWidth && !(suspectWidth == rhs.suspectWidth))
      return false;
    if (!(status == rhs.status))
      return false;
    return true;
  }
  bool operator != (const TubeWidthInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TubeWidthInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TubeWidthInfo &a, TubeWidthInfo &b);

std::ostream& operator<<(std::ostream& out, const TubeWidthInfo& obj);

typedef struct _TubeExistInfo__isset {
  _TubeExistInfo__isset() : isExist(false), status(true) {}
  bool isExist :1;
  bool status :1;
} _TubeExistInfo__isset;

/**
 * 试管有无信息结构体
 */
class TubeExistInfo : public virtual ::apache::thrift::TBase {
 public:

  TubeExistInfo(const TubeExistInfo&) noexcept;
  TubeExistInfo& operator=(const TubeExistInfo&) noexcept;
  TubeExistInfo() noexcept
                : isExist(0),
                  status(-1) {
  }

  virtual ~TubeExistInfo() noexcept;
  bool isExist;
  int32_t status;

  _TubeExistInfo__isset __isset;

  void __set_isExist(const bool val);

  void __set_status(const int32_t val);

  bool operator == (const TubeExistInfo & rhs) const
  {
    if (__isset.isExist != rhs.__isset.isExist)
      return false;
    else if (__isset.isExist && !(isExist == rhs.isExist))
      return false;
    if (!(status == rhs.status))
      return false;
    return true;
  }
  bool operator != (const TubeExistInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TubeExistInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TubeExistInfo &a, TubeExistInfo &b);

std::ostream& operator<<(std::ostream& out, const TubeExistInfo& obj);

typedef struct _TubeHatColorInfo__isset {
  _TubeHatColorInfo__isset() : tubeHatColor(false), tubeHatHsv(false), status(true) {}
  bool tubeHatColor :1;
  bool tubeHatHsv :1;
  bool status :1;
} _TubeHatColorInfo__isset;

/**
 * 试管管帽颜色信息结构体
 */
class TubeHatColorInfo : public virtual ::apache::thrift::TBase {
 public:

  TubeHatColorInfo(const TubeHatColorInfo&) noexcept;
  TubeHatColorInfo& operator=(const TubeHatColorInfo&) noexcept;
  TubeHatColorInfo() noexcept
                   : tubeHatColor(static_cast<TubeHatColor::type>(0)),
                     status(-1) {
  }

  virtual ~TubeHatColorInfo() noexcept;
  /**
   * 
   * @see TubeHatColor
   */
  TubeHatColor::type tubeHatColor;
  TubeHatHSV tubeHatHsv;
  int32_t status;

  _TubeHatColorInfo__isset __isset;

  void __set_tubeHatColor(const TubeHatColor::type val);

  void __set_tubeHatHsv(const TubeHatHSV& val);

  void __set_status(const int32_t val);

  bool operator == (const TubeHatColorInfo & rhs) const
  {
    if (__isset.tubeHatColor != rhs.__isset.tubeHatColor)
      return false;
    else if (__isset.tubeHatColor && !(tubeHatColor == rhs.tubeHatColor))
      return false;
    if (__isset.tubeHatHsv != rhs.__isset.tubeHatHsv)
      return false;
    else if (__isset.tubeHatHsv && !(tubeHatHsv == rhs.tubeHatHsv))
      return false;
    if (!(status == rhs.status))
      return false;
    return true;
  }
  bool operator != (const TubeHatColorInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TubeHatColorInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TubeHatColorInfo &a, TubeHatColorInfo &b);

std::ostream& operator<<(std::ostream& out, const TubeHatColorInfo& obj);

typedef struct _TubeTypeInfo__isset {
  _TubeTypeInfo__isset() : tubeType(false), status(true) {}
  bool tubeType :1;
  bool status :1;
} _TubeTypeInfo__isset;

/**
 * 试管类型信息结构体
 */
class TubeTypeInfo : public virtual ::apache::thrift::TBase {
 public:

  TubeTypeInfo(const TubeTypeInfo&) noexcept;
  TubeTypeInfo& operator=(const TubeTypeInfo&) noexcept;
  TubeTypeInfo() noexcept
               : tubeType(static_cast<TubeType::type>(0)),
                 status(-1) {
  }

  virtual ~TubeTypeInfo() noexcept;
  /**
   * 
   * @see TubeType
   */
  TubeType::type tubeType;
  int32_t status;

  _TubeTypeInfo__isset __isset;

  void __set_tubeType(const TubeType::type val);

  void __set_status(const int32_t val);

  bool operator == (const TubeTypeInfo & rhs) const
  {
    if (__isset.tubeType != rhs.__isset.tubeType)
      return false;
    else if (__isset.tubeType && !(tubeType == rhs.tubeType))
      return false;
    if (!(status == rhs.status))
      return false;
    return true;
  }
  bool operator != (const TubeTypeInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TubeTypeInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TubeTypeInfo &a, TubeTypeInfo &b);

std::ostream& operator<<(std::ostream& out, const TubeTypeInfo& obj);

typedef struct _HatTypeInfo__isset {
  _HatTypeInfo__isset() : hatType(false), status(true) {}
  bool hatType :1;
  bool status :1;
} _HatTypeInfo__isset;

class HatTypeInfo : public virtual ::apache::thrift::TBase {
 public:

  HatTypeInfo(const HatTypeInfo&) noexcept;
  HatTypeInfo& operator=(const HatTypeInfo&) noexcept;
  HatTypeInfo() noexcept
              : hatType(static_cast<HatType::type>(0)),
                status(-1) {
  }

  virtual ~HatTypeInfo() noexcept;
  /**
   * 
   * @see HatType
   */
  HatType::type hatType;
  int32_t status;

  _HatTypeInfo__isset __isset;

  void __set_hatType(const HatType::type val);

  void __set_status(const int32_t val);

  bool operator == (const HatTypeInfo & rhs) const
  {
    if (__isset.hatType != rhs.__isset.hatType)
      return false;
    else if (__isset.hatType && !(hatType == rhs.hatType))
      return false;
    if (!(status == rhs.status))
      return false;
    return true;
  }
  bool operator != (const HatTypeInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HatTypeInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(HatTypeInfo &a, HatTypeInfo &b);

std::ostream& operator<<(std::ostream& out, const HatTypeInfo& obj);

typedef struct _TubeTiltInfo__isset {
  _TubeTiltInfo__isset() : tubeBodyTilt(false), tubeHatTilt(false), tubeHatRelativeToBodyTilt(false), status(true) {}
  bool tubeBodyTilt :1;
  bool tubeHatTilt :1;
  bool tubeHatRelativeToBodyTilt :1;
  bool status :1;
} _TubeTiltInfo__isset;

/**
 * 试管倾斜信息结构体
 */
class TubeTiltInfo : public virtual ::apache::thrift::TBase {
 public:

  TubeTiltInfo(const TubeTiltInfo&) noexcept;
  TubeTiltInfo& operator=(const TubeTiltInfo&) noexcept;
  TubeTiltInfo() noexcept
               : tubeBodyTilt(0),
                 tubeHatTilt(0),
                 tubeHatRelativeToBodyTilt(0),
                 status(-1) {
  }

  virtual ~TubeTiltInfo() noexcept;
  double tubeBodyTilt;
  double tubeHatTilt;
  double tubeHatRelativeToBodyTilt;
  int32_t status;

  _TubeTiltInfo__isset __isset;

  void __set_tubeBodyTilt(const double val);

  void __set_tubeHatTilt(const double val);

  void __set_tubeHatRelativeToBodyTilt(const double val);

  void __set_status(const int32_t val);

  bool operator == (const TubeTiltInfo & rhs) const
  {
    if (__isset.tubeBodyTilt != rhs.__isset.tubeBodyTilt)
      return false;
    else if (__isset.tubeBodyTilt && !(tubeBodyTilt == rhs.tubeBodyTilt))
      return false;
    if (__isset.tubeHatTilt != rhs.__isset.tubeHatTilt)
      return false;
    else if (__isset.tubeHatTilt && !(tubeHatTilt == rhs.tubeHatTilt))
      return false;
    if (__isset.tubeHatRelativeToBodyTilt != rhs.__isset.tubeHatRelativeToBodyTilt)
      return false;
    else if (__isset.tubeHatRelativeToBodyTilt && !(tubeHatRelativeToBodyTilt == rhs.tubeHatRelativeToBodyTilt))
      return false;
    if (!(status == rhs.status))
      return false;
    return true;
  }
  bool operator != (const TubeTiltInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TubeTiltInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TubeTiltInfo &a, TubeTiltInfo &b);

std::ostream& operator<<(std::ostream& out, const TubeTiltInfo& obj);

typedef struct _SerumIndexInfo__isset {
  _SerumIndexInfo__isset() : hemolysisLevel(false), icterusLevel(false), lipemiaLevel(false), status(true) {}
  bool hemolysisLevel :1;
  bool icterusLevel :1;
  bool lipemiaLevel :1;
  bool status :1;
} _SerumIndexInfo__isset;

/**
 * 血清指数信息结构体
 */
class SerumIndexInfo : public virtual ::apache::thrift::TBase {
 public:

  SerumIndexInfo(const SerumIndexInfo&) noexcept;
  SerumIndexInfo& operator=(const SerumIndexInfo&) noexcept;
  SerumIndexInfo() noexcept
                 : hemolysisLevel(0),
                   icterusLevel(0),
                   lipemiaLevel(0),
                   status(-1) {
  }

  virtual ~SerumIndexInfo() noexcept;
  double hemolysisLevel;
  double icterusLevel;
  double lipemiaLevel;
  int32_t status;

  _SerumIndexInfo__isset __isset;

  void __set_hemolysisLevel(const double val);

  void __set_icterusLevel(const double val);

  void __set_lipemiaLevel(const double val);

  void __set_status(const int32_t val);

  bool operator == (const SerumIndexInfo & rhs) const
  {
    if (__isset.hemolysisLevel != rhs.__isset.hemolysisLevel)
      return false;
    else if (__isset.hemolysisLevel && !(hemolysisLevel == rhs.hemolysisLevel))
      return false;
    if (__isset.icterusLevel != rhs.__isset.icterusLevel)
      return false;
    else if (__isset.icterusLevel && !(icterusLevel == rhs.icterusLevel))
      return false;
    if (__isset.lipemiaLevel != rhs.__isset.lipemiaLevel)
      return false;
    else if (__isset.lipemiaLevel && !(lipemiaLevel == rhs.lipemiaLevel))
      return false;
    if (!(status == rhs.status))
      return false;
    return true;
  }
  bool operator != (const SerumIndexInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SerumIndexInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(SerumIndexInfo &a, SerumIndexInfo &b);

std::ostream& operator<<(std::ostream& out, const SerumIndexInfo& obj);

typedef struct _SampleHeight__isset {
  _SampleHeight__isset() : serumHeight(false), gelHeight(false), cellsHeight(false), allSampleHeight(false) {}
  bool serumHeight :1;
  bool gelHeight :1;
  bool cellsHeight :1;
  bool allSampleHeight :1;
} _SampleHeight__isset;

/**
 * 离心后样本分层高度结构体（单位：mm，距离管底高度）
 */
class SampleHeight : public virtual ::apache::thrift::TBase {
 public:

  SampleHeight(const SampleHeight&) noexcept;
  SampleHeight& operator=(const SampleHeight&) noexcept;
  SampleHeight() noexcept
               : serumHeight(0),
                 gelHeight(0),
                 cellsHeight(0),
                 allSampleHeight(0) {
  }

  virtual ~SampleHeight() noexcept;
  double serumHeight;
  double gelHeight;
  double cellsHeight;
  double allSampleHeight;

  _SampleHeight__isset __isset;

  void __set_serumHeight(const double val);

  void __set_gelHeight(const double val);

  void __set_cellsHeight(const double val);

  void __set_allSampleHeight(const double val);

  bool operator == (const SampleHeight & rhs) const
  {
    if (!(serumHeight == rhs.serumHeight))
      return false;
    if (!(gelHeight == rhs.gelHeight))
      return false;
    if (!(cellsHeight == rhs.cellsHeight))
      return false;
    if (!(allSampleHeight == rhs.allSampleHeight))
      return false;
    return true;
  }
  bool operator != (const SampleHeight &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SampleHeight & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(SampleHeight &a, SampleHeight &b);

std::ostream& operator<<(std::ostream& out, const SampleHeight& obj);

typedef struct _SampleVolume__isset {
  _SampleVolume__isset() : serumVolume(false), gelVolume(false), cellsVolume(false), allSampleVolume(false) {}
  bool serumVolume :1;
  bool gelVolume :1;
  bool cellsVolume :1;
  bool allSampleVolume :1;
} _SampleVolume__isset;

/**
 * 离心后样本分层体积结构体（单位：mL）
 */
class SampleVolume : public virtual ::apache::thrift::TBase {
 public:

  SampleVolume(const SampleVolume&) noexcept;
  SampleVolume& operator=(const SampleVolume&) noexcept;
  SampleVolume() noexcept
               : serumVolume(0),
                 gelVolume(0),
                 cellsVolume(0),
                 allSampleVolume(0) {
  }

  virtual ~SampleVolume() noexcept;
  double serumVolume;
  double gelVolume;
  double cellsVolume;
  double allSampleVolume;

  _SampleVolume__isset __isset;

  void __set_serumVolume(const double val);

  void __set_gelVolume(const double val);

  void __set_cellsVolume(const double val);

  void __set_allSampleVolume(const double val);

  bool operator == (const SampleVolume & rhs) const
  {
    if (!(serumVolume == rhs.serumVolume))
      return false;
    if (!(gelVolume == rhs.gelVolume))
      return false;
    if (!(cellsVolume == rhs.cellsVolume))
      return false;
    if (!(allSampleVolume == rhs.allSampleVolume))
      return false;
    return true;
  }
  bool operator != (const SampleVolume &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SampleVolume & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(SampleVolume &a, SampleVolume &b);

std::ostream& operator<<(std::ostream& out, const SampleVolume& obj);

typedef struct _SampleSizeInfo__isset {
  _SampleSizeInfo__isset() : height(false), volume(false), status(true) {}
  bool height :1;
  bool volume :1;
  bool status :1;
} _SampleSizeInfo__isset;

/**
 * 样本量信息结构体
 */
class SampleSizeInfo : public virtual ::apache::thrift::TBase {
 public:

  SampleSizeInfo(const SampleSizeInfo&) noexcept;
  SampleSizeInfo& operator=(const SampleSizeInfo&) noexcept;
  SampleSizeInfo() noexcept
                 : status(-1) {
  }

  virtual ~SampleSizeInfo() noexcept;
  SampleHeight height;
  SampleVolume volume;
  int32_t status;

  _SampleSizeInfo__isset __isset;

  void __set_height(const SampleHeight& val);

  void __set_volume(const SampleVolume& val);

  void __set_status(const int32_t val);

  bool operator == (const SampleSizeInfo & rhs) const
  {
    if (__isset.height != rhs.__isset.height)
      return false;
    else if (__isset.height && !(height == rhs.height))
      return false;
    if (__isset.volume != rhs.__isset.volume)
      return false;
    else if (__isset.volume && !(volume == rhs.volume))
      return false;
    if (!(status == rhs.status))
      return false;
    return true;
  }
  bool operator != (const SampleSizeInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SampleSizeInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(SampleSizeInfo &a, SampleSizeInfo &b);

std::ostream& operator<<(std::ostream& out, const SampleSizeInfo& obj);

typedef struct _SampleCentrifugedInfo__isset {
  _SampleCentrifugedInfo__isset() : isCentrifuged(false), status(true) {}
  bool isCentrifuged :1;
  bool status :1;
} _SampleCentrifugedInfo__isset;

/**
 * 离心状态信息结构体
 */
class SampleCentrifugedInfo : public virtual ::apache::thrift::TBase {
 public:

  SampleCentrifugedInfo(const SampleCentrifugedInfo&) noexcept;
  SampleCentrifugedInfo& operator=(const SampleCentrifugedInfo&) noexcept;
  SampleCentrifugedInfo() noexcept
                        : isCentrifuged(0),
                          status(-1) {
  }

  virtual ~SampleCentrifugedInfo() noexcept;
  bool isCentrifuged;
  int32_t status;

  _SampleCentrifugedInfo__isset __isset;

  void __set_isCentrifuged(const bool val);

  void __set_status(const int32_t val);

  bool operator == (const SampleCentrifugedInfo & rhs) const
  {
    if (__isset.isCentrifuged != rhs.__isset.isCentrifuged)
      return false;
    else if (__isset.isCentrifuged && !(isCentrifuged == rhs.isCentrifuged))
      return false;
    if (!(status == rhs.status))
      return false;
    return true;
  }
  bool operator != (const SampleCentrifugedInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SampleCentrifugedInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(SampleCentrifugedInfo &a, SampleCentrifugedInfo &b);

std::ostream& operator<<(std::ostream& out, const SampleCentrifugedInfo& obj);

typedef struct _SampleCentrifugedQualityInfo__isset {
  _SampleCentrifugedQualityInfo__isset() : hasBubble(false), hasGrume(false), hasFibers(false), status(true) {}
  bool hasBubble :1;
  bool hasGrume :1;
  bool hasFibers :1;
  bool status :1;
} _SampleCentrifugedQualityInfo__isset;

/**
 * 离心质量判定信息结构体
 */
class SampleCentrifugedQualityInfo : public virtual ::apache::thrift::TBase {
 public:

  SampleCentrifugedQualityInfo(const SampleCentrifugedQualityInfo&) noexcept;
  SampleCentrifugedQualityInfo& operator=(const SampleCentrifugedQualityInfo&) noexcept;
  SampleCentrifugedQualityInfo() noexcept
                               : hasBubble(0),
                                 hasGrume(0),
                                 hasFibers(0),
                                 status(-1) {
  }

  virtual ~SampleCentrifugedQualityInfo() noexcept;
  bool hasBubble;
  bool hasGrume;
  bool hasFibers;
  int32_t status;

  _SampleCentrifugedQualityInfo__isset __isset;

  void __set_hasBubble(const bool val);

  void __set_hasGrume(const bool val);

  void __set_hasFibers(const bool val);

  void __set_status(const int32_t val);

  bool operator == (const SampleCentrifugedQualityInfo & rhs) const
  {
    if (__isset.hasBubble != rhs.__isset.hasBubble)
      return false;
    else if (__isset.hasBubble && !(hasBubble == rhs.hasBubble))
      return false;
    if (__isset.hasGrume != rhs.__isset.hasGrume)
      return false;
    else if (__isset.hasGrume && !(hasGrume == rhs.hasGrume))
      return false;
    if (__isset.hasFibers != rhs.__isset.hasFibers)
      return false;
    else if (__isset.hasFibers && !(hasFibers == rhs.hasFibers))
      return false;
    if (!(status == rhs.status))
      return false;
    return true;
  }
  bool operator != (const SampleCentrifugedQualityInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SampleCentrifugedQualityInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(SampleCentrifugedQualityInfo &a, SampleCentrifugedQualityInfo &b);

std::ostream& operator<<(std::ostream& out, const SampleCentrifugedQualityInfo& obj);

typedef struct _TubeOverHeadAxisInfo__isset {
  _TubeOverHeadAxisInfo__isset() : tubeAxis(false), status(true) {}
  bool tubeAxis :1;
  bool status :1;
} _TubeOverHeadAxisInfo__isset;

/**
 * 俯拍试管坐标信息结构体
 */
class TubeOverHeadAxisInfo : public virtual ::apache::thrift::TBase {
 public:

  TubeOverHeadAxisInfo(const TubeOverHeadAxisInfo&);
  TubeOverHeadAxisInfo& operator=(const TubeOverHeadAxisInfo&);
  TubeOverHeadAxisInfo() noexcept
                       : status(-1) {
  }

  virtual ~TubeOverHeadAxisInfo() noexcept;
  std::vector<Bbox>  tubeAxis;
  int32_t status;

  _TubeOverHeadAxisInfo__isset __isset;

  void __set_tubeAxis(const std::vector<Bbox> & val);

  void __set_status(const int32_t val);

  bool operator == (const TubeOverHeadAxisInfo & rhs) const
  {
    if (__isset.tubeAxis != rhs.__isset.tubeAxis)
      return false;
    else if (__isset.tubeAxis && !(tubeAxis == rhs.tubeAxis))
      return false;
    if (!(status == rhs.status))
      return false;
    return true;
  }
  bool operator != (const TubeOverHeadAxisInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TubeOverHeadAxisInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TubeOverHeadAxisInfo &a, TubeOverHeadAxisInfo &b);

std::ostream& operator<<(std::ostream& out, const TubeOverHeadAxisInfo& obj);

typedef struct _TubeOverHeadInfo__isset {
  _TubeOverHeadInfo__isset() : info(true), status(true) {}
  bool info :1;
  bool status :1;
} _TubeOverHeadInfo__isset;

/**
 * 俯拍试管有无信息结构体
 */
class TubeOverHeadInfo : public virtual ::apache::thrift::TBase {
 public:

  TubeOverHeadInfo(const TubeOverHeadInfo&);
  TubeOverHeadInfo& operator=(const TubeOverHeadInfo&);
  TubeOverHeadInfo() noexcept
                   : status(-1) {

  }

  virtual ~TubeOverHeadInfo() noexcept;
  std::vector<TubeOverHeadStatus::type>  info;
  int32_t status;

  _TubeOverHeadInfo__isset __isset;

  void __set_info(const std::vector<TubeOverHeadStatus::type> & val);

  void __set_status(const int32_t val);

  bool operator == (const TubeOverHeadInfo & rhs) const
  {
    if (__isset.info != rhs.__isset.info)
      return false;
    else if (__isset.info && !(info == rhs.info))
      return false;
    if (!(status == rhs.status))
      return false;
    return true;
  }
  bool operator != (const TubeOverHeadInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TubeOverHeadInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TubeOverHeadInfo &a, TubeOverHeadInfo &b);

std::ostream& operator<<(std::ostream& out, const TubeOverHeadInfo& obj);

typedef struct _TubeOverHeadColor__isset {
  _TubeOverHeadColor__isset() : colors(true), status(true) {}
  bool colors :1;
  bool status :1;
} _TubeOverHeadColor__isset;

/**
 * 俯拍管帽颜色信息结构体
 */
class TubeOverHeadColor : public virtual ::apache::thrift::TBase {
 public:

  TubeOverHeadColor(const TubeOverHeadColor&);
  TubeOverHeadColor& operator=(const TubeOverHeadColor&);
  TubeOverHeadColor() noexcept
                    : status(-1) {

  }

  virtual ~TubeOverHeadColor() noexcept;
  std::vector<TubeHatColorInfo>  colors;
  int32_t status;

  _TubeOverHeadColor__isset __isset;

  void __set_colors(const std::vector<TubeHatColorInfo> & val);

  void __set_status(const int32_t val);

  bool operator == (const TubeOverHeadColor & rhs) const
  {
    if (__isset.colors != rhs.__isset.colors)
      return false;
    else if (__isset.colors && !(colors == rhs.colors))
      return false;
    if (!(status == rhs.status))
      return false;
    return true;
  }
  bool operator != (const TubeOverHeadColor &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TubeOverHeadColor & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TubeOverHeadColor &a, TubeOverHeadColor &b);

std::ostream& operator<<(std::ostream& out, const TubeOverHeadColor& obj);

typedef struct _TaskResult__isset {
  _TaskResult__isset() : barcode(false), bestBarcodeImage(false), bestLiquidImage(false), tubeHeight(false), tubeWidth(false), tubeExist(false), tubeHatColor(false), tubeType(false), hatType(false), tubeTilt(false), serumIndex(false), sampleSize(false), sampleCentrifuged(false), sampleCentrifugedQuality(false), tubeOverHeadAxis(false), tubeOverHead(false), tubeOverHeadColor(false) {}
  bool barcode :1;
  bool bestBarcodeImage :1;
  bool bestLiquidImage :1;
  bool tubeHeight :1;
  bool tubeWidth :1;
  bool tubeExist :1;
  bool tubeHatColor :1;
  bool tubeType :1;
  bool hatType :1;
  bool tubeTilt :1;
  bool serumIndex :1;
  bool sampleSize :1;
  bool sampleCentrifuged :1;
  bool sampleCentrifugedQuality :1;
  bool tubeOverHeadAxis :1;
  bool tubeOverHead :1;
  bool tubeOverHeadColor :1;
} _TaskResult__isset;

/**
 * 任务执行结果结构体
 * 根据任务类型返回对应字段（其他字段为null）
 */
class TaskResult : public virtual ::apache::thrift::TBase {
 public:

  TaskResult(const TaskResult&);
  TaskResult& operator=(const TaskResult&);
  TaskResult() noexcept {
  }

  virtual ~TaskResult() noexcept;
  BarcodeInfo barcode;
  BestBarcodeImageInfo bestBarcodeImage;
  BestLiquidImageInfo bestLiquidImage;
  TubeHeightInfo tubeHeight;
  TubeWidthInfo tubeWidth;
  TubeExistInfo tubeExist;
  TubeHatColorInfo tubeHatColor;
  TubeTypeInfo tubeType;
  HatTypeInfo hatType;
  TubeTiltInfo tubeTilt;
  SerumIndexInfo serumIndex;
  SampleSizeInfo sampleSize;
  SampleCentrifugedInfo sampleCentrifuged;
  SampleCentrifugedQualityInfo sampleCentrifugedQuality;
  TubeOverHeadAxisInfo tubeOverHeadAxis;
  TubeOverHeadInfo tubeOverHead;
  TubeOverHeadColor tubeOverHeadColor;

  _TaskResult__isset __isset;

  void __set_barcode(const BarcodeInfo& val);

  void __set_bestBarcodeImage(const BestBarcodeImageInfo& val);

  void __set_bestLiquidImage(const BestLiquidImageInfo& val);

  void __set_tubeHeight(const TubeHeightInfo& val);

  void __set_tubeWidth(const TubeWidthInfo& val);

  void __set_tubeExist(const TubeExistInfo& val);

  void __set_tubeHatColor(const TubeHatColorInfo& val);

  void __set_tubeType(const TubeTypeInfo& val);

  void __set_hatType(const HatTypeInfo& val);

  void __set_tubeTilt(const TubeTiltInfo& val);

  void __set_serumIndex(const SerumIndexInfo& val);

  void __set_sampleSize(const SampleSizeInfo& val);

  void __set_sampleCentrifuged(const SampleCentrifugedInfo& val);

  void __set_sampleCentrifugedQuality(const SampleCentrifugedQualityInfo& val);

  void __set_tubeOverHeadAxis(const TubeOverHeadAxisInfo& val);

  void __set_tubeOverHead(const TubeOverHeadInfo& val);

  void __set_tubeOverHeadColor(const TubeOverHeadColor& val);

  bool operator == (const TaskResult & rhs) const
  {
    if (__isset.barcode != rhs.__isset.barcode)
      return false;
    else if (__isset.barcode && !(barcode == rhs.barcode))
      return false;
    if (__isset.bestBarcodeImage != rhs.__isset.bestBarcodeImage)
      return false;
    else if (__isset.bestBarcodeImage && !(bestBarcodeImage == rhs.bestBarcodeImage))
      return false;
    if (__isset.bestLiquidImage != rhs.__isset.bestLiquidImage)
      return false;
    else if (__isset.bestLiquidImage && !(bestLiquidImage == rhs.bestLiquidImage))
      return false;
    if (__isset.tubeHeight != rhs.__isset.tubeHeight)
      return false;
    else if (__isset.tubeHeight && !(tubeHeight == rhs.tubeHeight))
      return false;
    if (__isset.tubeWidth != rhs.__isset.tubeWidth)
      return false;
    else if (__isset.tubeWidth && !(tubeWidth == rhs.tubeWidth))
      return false;
    if (__isset.tubeExist != rhs.__isset.tubeExist)
      return false;
    else if (__isset.tubeExist && !(tubeExist == rhs.tubeExist))
      return false;
    if (__isset.tubeHatColor != rhs.__isset.tubeHatColor)
      return false;
    else if (__isset.tubeHatColor && !(tubeHatColor == rhs.tubeHatColor))
      return false;
    if (__isset.tubeType != rhs.__isset.tubeType)
      return false;
    else if (__isset.tubeType && !(tubeType == rhs.tubeType))
      return false;
    if (__isset.hatType != rhs.__isset.hatType)
      return false;
    else if (__isset.hatType && !(hatType == rhs.hatType))
      return false;
    if (__isset.tubeTilt != rhs.__isset.tubeTilt)
      return false;
    else if (__isset.tubeTilt && !(tubeTilt == rhs.tubeTilt))
      return false;
    if (__isset.serumIndex != rhs.__isset.serumIndex)
      return false;
    else if (__isset.serumIndex && !(serumIndex == rhs.serumIndex))
      return false;
    if (__isset.sampleSize != rhs.__isset.sampleSize)
      return false;
    else if (__isset.sampleSize && !(sampleSize == rhs.sampleSize))
      return false;
    if (__isset.sampleCentrifuged != rhs.__isset.sampleCentrifuged)
      return false;
    else if (__isset.sampleCentrifuged && !(sampleCentrifuged == rhs.sampleCentrifuged))
      return false;
    if (__isset.sampleCentrifugedQuality != rhs.__isset.sampleCentrifugedQuality)
      return false;
    else if (__isset.sampleCentrifugedQuality && !(sampleCentrifugedQuality == rhs.sampleCentrifugedQuality))
      return false;
    if (__isset.tubeOverHeadAxis != rhs.__isset.tubeOverHeadAxis)
      return false;
    else if (__isset.tubeOverHeadAxis && !(tubeOverHeadAxis == rhs.tubeOverHeadAxis))
      return false;
    if (__isset.tubeOverHead != rhs.__isset.tubeOverHead)
      return false;
    else if (__isset.tubeOverHead && !(tubeOverHead == rhs.tubeOverHead))
      return false;
    if (__isset.tubeOverHeadColor != rhs.__isset.tubeOverHeadColor)
      return false;
    else if (__isset.tubeOverHeadColor && !(tubeOverHeadColor == rhs.tubeOverHeadColor))
      return false;
    return true;
  }
  bool operator != (const TaskResult &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TaskResult & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TaskResult &a, TaskResult &b);

std::ostream& operator<<(std::ostream& out, const TaskResult& obj);

typedef struct _TaskInfo__isset {
  _TaskInfo__isset() : taskId(false), taskType(false), state(true), mode(false), imageIn(false), retCode(false), imageOut(false), result(false) {}
  bool taskId :1;
  bool taskType :1;
  bool state :1;
  bool mode :1;
  bool imageIn :1;
  bool retCode :1;
  bool imageOut :1;
  bool result :1;
} _TaskInfo__isset;

/**
 * 任务信息结构体
 * 包含任务描述、状态及执行结果
 */
class TaskInfo : public virtual ::apache::thrift::TBase {
 public:

  TaskInfo(const TaskInfo&);
  TaskInfo& operator=(const TaskInfo&);
  TaskInfo() noexcept
           : taskId(),
             state((TaskState::type)0),
             mode(0),
             retCode(0) {
    state = (TaskState::type)0;

  }

  virtual ~TaskInfo() noexcept;
  std::string taskId;
  std::vector<TaskType::type>  taskType;
  /**
   * 
   * @see TaskState
   */
  TaskState::type state;
  int32_t mode;
  std::vector<ImageInfo>  imageIn;
  int32_t retCode;
  std::vector<ImageInfo>  imageOut;
  TaskResult result;

  _TaskInfo__isset __isset;

  void __set_taskId(const std::string& val);

  void __set_taskType(const std::vector<TaskType::type> & val);

  void __set_state(const TaskState::type val);

  void __set_mode(const int32_t val);

  void __set_imageIn(const std::vector<ImageInfo> & val);

  void __set_retCode(const int32_t val);

  void __set_imageOut(const std::vector<ImageInfo> & val);

  void __set_result(const TaskResult& val);

  bool operator == (const TaskInfo & rhs) const
  {
    if (!(taskId == rhs.taskId))
      return false;
    if (!(taskType == rhs.taskType))
      return false;
    if (!(state == rhs.state))
      return false;
    if (!(mode == rhs.mode))
      return false;
    if (__isset.imageIn != rhs.__isset.imageIn)
      return false;
    else if (__isset.imageIn && !(imageIn == rhs.imageIn))
      return false;
    if (__isset.retCode != rhs.__isset.retCode)
      return false;
    else if (__isset.retCode && !(retCode == rhs.retCode))
      return false;
    if (__isset.imageOut != rhs.__isset.imageOut)
      return false;
    else if (__isset.imageOut && !(imageOut == rhs.imageOut))
      return false;
    if (__isset.result != rhs.__isset.result)
      return false;
    else if (__isset.result && !(result == rhs.result))
      return false;
    return true;
  }
  bool operator != (const TaskInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TaskInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TaskInfo &a, TaskInfo &b);

std::ostream& operator<<(std::ostream& out, const TaskInfo& obj);

} // namespace

#endif
