/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef SampleRegLC_H
#define SampleRegLC_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "SampleReg_Interface_LC_types.h"

namespace SampleReg {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class SampleRegLCIf {
 public:
  virtual ~SampleRegLCIf() {}

  /**
   * 向上位机发送心跳
   * @param timeStamp 时间戳（毫秒级）
   * 
   * @param timeStamp
   */
  virtual void HeartbeatToLC(const int64_t timeStamp) = 0;

  /**
   * 发布通用操作指令
   * @param info 通用操作信息（包含指令及参数）
   * @return 0表示下发成功，非0表示错误码
   * 
   * @param info
   */
  virtual int32_t DistributeOper(const  ::SampleReg::GeneralOperInfo& info) = 0;

  /**
   * 发布任务指令
   * @param info 任务信息（包含任务ID、类型等）
   * @return 0表示下发成功，非0表示错误码
   * 
   * @param info
   */
  virtual int32_t DistributeTask(const  ::SampleReg::TaskInfo& info) = 0;

  /**
   * 获取当前任务信息
   * @return 任务详细信息
   */
  virtual void GetTaskInfo( ::SampleReg::TaskInfo& _return) = 0;

  /**
   * 获取当前设备信息
   * @return 设备运行状态等信息
   */
  virtual void GetDeviceInfo( ::SampleReg::DeviceInfo& _return) = 0;

  /**
   * 获取当前通用操作信息
   * @return 通用操作的执行状态及结果
   */
  virtual void GetOperInfo( ::SampleReg::GeneralOperInfo& _return) = 0;
};

class SampleRegLCIfFactory {
 public:
  typedef SampleRegLCIf Handler;

  virtual ~SampleRegLCIfFactory() {}

  virtual SampleRegLCIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(SampleRegLCIf* /* handler */) = 0;
  };

class SampleRegLCIfSingletonFactory : virtual public SampleRegLCIfFactory {
 public:
  SampleRegLCIfSingletonFactory(const ::std::shared_ptr<SampleRegLCIf>& iface) : iface_(iface) {}
  virtual ~SampleRegLCIfSingletonFactory() {}

  virtual SampleRegLCIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(SampleRegLCIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<SampleRegLCIf> iface_;
};

class SampleRegLCNull : virtual public SampleRegLCIf {
 public:
  virtual ~SampleRegLCNull() {}
  void HeartbeatToLC(const int64_t /* timeStamp */) override {
    return;
  }
  int32_t DistributeOper(const  ::SampleReg::GeneralOperInfo& /* info */) override {
    int32_t _return = 0;
    return _return;
  }
  int32_t DistributeTask(const  ::SampleReg::TaskInfo& /* info */) override {
    int32_t _return = 0;
    return _return;
  }
  void GetTaskInfo( ::SampleReg::TaskInfo& /* _return */) override {
    return;
  }
  void GetDeviceInfo( ::SampleReg::DeviceInfo& /* _return */) override {
    return;
  }
  void GetOperInfo( ::SampleReg::GeneralOperInfo& /* _return */) override {
    return;
  }
};

typedef struct _SampleRegLC_HeartbeatToLC_args__isset {
  _SampleRegLC_HeartbeatToLC_args__isset() : timeStamp(false) {}
  bool timeStamp :1;
} _SampleRegLC_HeartbeatToLC_args__isset;

class SampleRegLC_HeartbeatToLC_args {
 public:

  SampleRegLC_HeartbeatToLC_args(const SampleRegLC_HeartbeatToLC_args&) noexcept;
  SampleRegLC_HeartbeatToLC_args& operator=(const SampleRegLC_HeartbeatToLC_args&) noexcept;
  SampleRegLC_HeartbeatToLC_args() noexcept
                                 : timeStamp(0) {
  }

  virtual ~SampleRegLC_HeartbeatToLC_args() noexcept;
  int64_t timeStamp;

  _SampleRegLC_HeartbeatToLC_args__isset __isset;

  void __set_timeStamp(const int64_t val);

  bool operator == (const SampleRegLC_HeartbeatToLC_args & rhs) const
  {
    if (!(timeStamp == rhs.timeStamp))
      return false;
    return true;
  }
  bool operator != (const SampleRegLC_HeartbeatToLC_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SampleRegLC_HeartbeatToLC_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class SampleRegLC_HeartbeatToLC_pargs {
 public:


  virtual ~SampleRegLC_HeartbeatToLC_pargs() noexcept;
  const int64_t* timeStamp;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class SampleRegLC_HeartbeatToLC_result {
 public:

  SampleRegLC_HeartbeatToLC_result(const SampleRegLC_HeartbeatToLC_result&) noexcept;
  SampleRegLC_HeartbeatToLC_result& operator=(const SampleRegLC_HeartbeatToLC_result&) noexcept;
  SampleRegLC_HeartbeatToLC_result() noexcept {
  }

  virtual ~SampleRegLC_HeartbeatToLC_result() noexcept;

  bool operator == (const SampleRegLC_HeartbeatToLC_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const SampleRegLC_HeartbeatToLC_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SampleRegLC_HeartbeatToLC_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class SampleRegLC_HeartbeatToLC_presult {
 public:


  virtual ~SampleRegLC_HeartbeatToLC_presult() noexcept;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _SampleRegLC_DistributeOper_args__isset {
  _SampleRegLC_DistributeOper_args__isset() : info(false) {}
  bool info :1;
} _SampleRegLC_DistributeOper_args__isset;

class SampleRegLC_DistributeOper_args {
 public:

  SampleRegLC_DistributeOper_args(const SampleRegLC_DistributeOper_args&);
  SampleRegLC_DistributeOper_args& operator=(const SampleRegLC_DistributeOper_args&);
  SampleRegLC_DistributeOper_args() noexcept {
  }

  virtual ~SampleRegLC_DistributeOper_args() noexcept;
   ::SampleReg::GeneralOperInfo info;

  _SampleRegLC_DistributeOper_args__isset __isset;

  void __set_info(const  ::SampleReg::GeneralOperInfo& val);

  bool operator == (const SampleRegLC_DistributeOper_args & rhs) const
  {
    if (!(info == rhs.info))
      return false;
    return true;
  }
  bool operator != (const SampleRegLC_DistributeOper_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SampleRegLC_DistributeOper_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class SampleRegLC_DistributeOper_pargs {
 public:


  virtual ~SampleRegLC_DistributeOper_pargs() noexcept;
  const  ::SampleReg::GeneralOperInfo* info;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SampleRegLC_DistributeOper_result__isset {
  _SampleRegLC_DistributeOper_result__isset() : success(false) {}
  bool success :1;
} _SampleRegLC_DistributeOper_result__isset;

class SampleRegLC_DistributeOper_result {
 public:

  SampleRegLC_DistributeOper_result(const SampleRegLC_DistributeOper_result&) noexcept;
  SampleRegLC_DistributeOper_result& operator=(const SampleRegLC_DistributeOper_result&) noexcept;
  SampleRegLC_DistributeOper_result() noexcept
                                    : success(0) {
  }

  virtual ~SampleRegLC_DistributeOper_result() noexcept;
  int32_t success;

  _SampleRegLC_DistributeOper_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const SampleRegLC_DistributeOper_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const SampleRegLC_DistributeOper_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SampleRegLC_DistributeOper_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SampleRegLC_DistributeOper_presult__isset {
  _SampleRegLC_DistributeOper_presult__isset() : success(false) {}
  bool success :1;
} _SampleRegLC_DistributeOper_presult__isset;

class SampleRegLC_DistributeOper_presult {
 public:


  virtual ~SampleRegLC_DistributeOper_presult() noexcept;
  int32_t* success;

  _SampleRegLC_DistributeOper_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _SampleRegLC_DistributeTask_args__isset {
  _SampleRegLC_DistributeTask_args__isset() : info(false) {}
  bool info :1;
} _SampleRegLC_DistributeTask_args__isset;

class SampleRegLC_DistributeTask_args {
 public:

  SampleRegLC_DistributeTask_args(const SampleRegLC_DistributeTask_args&);
  SampleRegLC_DistributeTask_args& operator=(const SampleRegLC_DistributeTask_args&);
  SampleRegLC_DistributeTask_args() noexcept {
  }

  virtual ~SampleRegLC_DistributeTask_args() noexcept;
   ::SampleReg::TaskInfo info;

  _SampleRegLC_DistributeTask_args__isset __isset;

  void __set_info(const  ::SampleReg::TaskInfo& val);

  bool operator == (const SampleRegLC_DistributeTask_args & rhs) const
  {
    if (!(info == rhs.info))
      return false;
    return true;
  }
  bool operator != (const SampleRegLC_DistributeTask_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SampleRegLC_DistributeTask_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class SampleRegLC_DistributeTask_pargs {
 public:


  virtual ~SampleRegLC_DistributeTask_pargs() noexcept;
  const  ::SampleReg::TaskInfo* info;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SampleRegLC_DistributeTask_result__isset {
  _SampleRegLC_DistributeTask_result__isset() : success(false) {}
  bool success :1;
} _SampleRegLC_DistributeTask_result__isset;

class SampleRegLC_DistributeTask_result {
 public:

  SampleRegLC_DistributeTask_result(const SampleRegLC_DistributeTask_result&) noexcept;
  SampleRegLC_DistributeTask_result& operator=(const SampleRegLC_DistributeTask_result&) noexcept;
  SampleRegLC_DistributeTask_result() noexcept
                                    : success(0) {
  }

  virtual ~SampleRegLC_DistributeTask_result() noexcept;
  int32_t success;

  _SampleRegLC_DistributeTask_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const SampleRegLC_DistributeTask_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const SampleRegLC_DistributeTask_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SampleRegLC_DistributeTask_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SampleRegLC_DistributeTask_presult__isset {
  _SampleRegLC_DistributeTask_presult__isset() : success(false) {}
  bool success :1;
} _SampleRegLC_DistributeTask_presult__isset;

class SampleRegLC_DistributeTask_presult {
 public:


  virtual ~SampleRegLC_DistributeTask_presult() noexcept;
  int32_t* success;

  _SampleRegLC_DistributeTask_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class SampleRegLC_GetTaskInfo_args {
 public:

  SampleRegLC_GetTaskInfo_args(const SampleRegLC_GetTaskInfo_args&) noexcept;
  SampleRegLC_GetTaskInfo_args& operator=(const SampleRegLC_GetTaskInfo_args&) noexcept;
  SampleRegLC_GetTaskInfo_args() noexcept {
  }

  virtual ~SampleRegLC_GetTaskInfo_args() noexcept;

  bool operator == (const SampleRegLC_GetTaskInfo_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const SampleRegLC_GetTaskInfo_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SampleRegLC_GetTaskInfo_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class SampleRegLC_GetTaskInfo_pargs {
 public:


  virtual ~SampleRegLC_GetTaskInfo_pargs() noexcept;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SampleRegLC_GetTaskInfo_result__isset {
  _SampleRegLC_GetTaskInfo_result__isset() : success(false) {}
  bool success :1;
} _SampleRegLC_GetTaskInfo_result__isset;

class SampleRegLC_GetTaskInfo_result {
 public:

  SampleRegLC_GetTaskInfo_result(const SampleRegLC_GetTaskInfo_result&);
  SampleRegLC_GetTaskInfo_result& operator=(const SampleRegLC_GetTaskInfo_result&);
  SampleRegLC_GetTaskInfo_result() noexcept {
  }

  virtual ~SampleRegLC_GetTaskInfo_result() noexcept;
   ::SampleReg::TaskInfo success;

  _SampleRegLC_GetTaskInfo_result__isset __isset;

  void __set_success(const  ::SampleReg::TaskInfo& val);

  bool operator == (const SampleRegLC_GetTaskInfo_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const SampleRegLC_GetTaskInfo_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SampleRegLC_GetTaskInfo_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SampleRegLC_GetTaskInfo_presult__isset {
  _SampleRegLC_GetTaskInfo_presult__isset() : success(false) {}
  bool success :1;
} _SampleRegLC_GetTaskInfo_presult__isset;

class SampleRegLC_GetTaskInfo_presult {
 public:


  virtual ~SampleRegLC_GetTaskInfo_presult() noexcept;
   ::SampleReg::TaskInfo* success;

  _SampleRegLC_GetTaskInfo_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class SampleRegLC_GetDeviceInfo_args {
 public:

  SampleRegLC_GetDeviceInfo_args(const SampleRegLC_GetDeviceInfo_args&) noexcept;
  SampleRegLC_GetDeviceInfo_args& operator=(const SampleRegLC_GetDeviceInfo_args&) noexcept;
  SampleRegLC_GetDeviceInfo_args() noexcept {
  }

  virtual ~SampleRegLC_GetDeviceInfo_args() noexcept;

  bool operator == (const SampleRegLC_GetDeviceInfo_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const SampleRegLC_GetDeviceInfo_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SampleRegLC_GetDeviceInfo_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class SampleRegLC_GetDeviceInfo_pargs {
 public:


  virtual ~SampleRegLC_GetDeviceInfo_pargs() noexcept;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SampleRegLC_GetDeviceInfo_result__isset {
  _SampleRegLC_GetDeviceInfo_result__isset() : success(false) {}
  bool success :1;
} _SampleRegLC_GetDeviceInfo_result__isset;

class SampleRegLC_GetDeviceInfo_result {
 public:

  SampleRegLC_GetDeviceInfo_result(const SampleRegLC_GetDeviceInfo_result&) noexcept;
  SampleRegLC_GetDeviceInfo_result& operator=(const SampleRegLC_GetDeviceInfo_result&) noexcept;
  SampleRegLC_GetDeviceInfo_result() noexcept {
  }

  virtual ~SampleRegLC_GetDeviceInfo_result() noexcept;
   ::SampleReg::DeviceInfo success;

  _SampleRegLC_GetDeviceInfo_result__isset __isset;

  void __set_success(const  ::SampleReg::DeviceInfo& val);

  bool operator == (const SampleRegLC_GetDeviceInfo_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const SampleRegLC_GetDeviceInfo_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SampleRegLC_GetDeviceInfo_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SampleRegLC_GetDeviceInfo_presult__isset {
  _SampleRegLC_GetDeviceInfo_presult__isset() : success(false) {}
  bool success :1;
} _SampleRegLC_GetDeviceInfo_presult__isset;

class SampleRegLC_GetDeviceInfo_presult {
 public:


  virtual ~SampleRegLC_GetDeviceInfo_presult() noexcept;
   ::SampleReg::DeviceInfo* success;

  _SampleRegLC_GetDeviceInfo_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class SampleRegLC_GetOperInfo_args {
 public:

  SampleRegLC_GetOperInfo_args(const SampleRegLC_GetOperInfo_args&) noexcept;
  SampleRegLC_GetOperInfo_args& operator=(const SampleRegLC_GetOperInfo_args&) noexcept;
  SampleRegLC_GetOperInfo_args() noexcept {
  }

  virtual ~SampleRegLC_GetOperInfo_args() noexcept;

  bool operator == (const SampleRegLC_GetOperInfo_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const SampleRegLC_GetOperInfo_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SampleRegLC_GetOperInfo_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class SampleRegLC_GetOperInfo_pargs {
 public:


  virtual ~SampleRegLC_GetOperInfo_pargs() noexcept;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SampleRegLC_GetOperInfo_result__isset {
  _SampleRegLC_GetOperInfo_result__isset() : success(false) {}
  bool success :1;
} _SampleRegLC_GetOperInfo_result__isset;

class SampleRegLC_GetOperInfo_result {
 public:

  SampleRegLC_GetOperInfo_result(const SampleRegLC_GetOperInfo_result&);
  SampleRegLC_GetOperInfo_result& operator=(const SampleRegLC_GetOperInfo_result&);
  SampleRegLC_GetOperInfo_result() noexcept {
  }

  virtual ~SampleRegLC_GetOperInfo_result() noexcept;
   ::SampleReg::GeneralOperInfo success;

  _SampleRegLC_GetOperInfo_result__isset __isset;

  void __set_success(const  ::SampleReg::GeneralOperInfo& val);

  bool operator == (const SampleRegLC_GetOperInfo_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const SampleRegLC_GetOperInfo_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SampleRegLC_GetOperInfo_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SampleRegLC_GetOperInfo_presult__isset {
  _SampleRegLC_GetOperInfo_presult__isset() : success(false) {}
  bool success :1;
} _SampleRegLC_GetOperInfo_presult__isset;

class SampleRegLC_GetOperInfo_presult {
 public:


  virtual ~SampleRegLC_GetOperInfo_presult() noexcept;
   ::SampleReg::GeneralOperInfo* success;

  _SampleRegLC_GetOperInfo_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class SampleRegLCClient : virtual public SampleRegLCIf {
 public:
  SampleRegLCClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  SampleRegLCClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  /**
   * 向上位机发送心跳
   * @param timeStamp 时间戳（毫秒级）
   * 
   * @param timeStamp
   */
  void HeartbeatToLC(const int64_t timeStamp) override;
  void send_HeartbeatToLC(const int64_t timeStamp);
  void recv_HeartbeatToLC();
  /**
   * 发布通用操作指令
   * @param info 通用操作信息（包含指令及参数）
   * @return 0表示下发成功，非0表示错误码
   * 
   * @param info
   */
  int32_t DistributeOper(const  ::SampleReg::GeneralOperInfo& info) override;
  void send_DistributeOper(const  ::SampleReg::GeneralOperInfo& info);
  int32_t recv_DistributeOper();
  /**
   * 发布任务指令
   * @param info 任务信息（包含任务ID、类型等）
   * @return 0表示下发成功，非0表示错误码
   * 
   * @param info
   */
  int32_t DistributeTask(const  ::SampleReg::TaskInfo& info) override;
  void send_DistributeTask(const  ::SampleReg::TaskInfo& info);
  int32_t recv_DistributeTask();
  /**
   * 获取当前任务信息
   * @return 任务详细信息
   */
  void GetTaskInfo( ::SampleReg::TaskInfo& _return) override;
  void send_GetTaskInfo();
  void recv_GetTaskInfo( ::SampleReg::TaskInfo& _return);
  /**
   * 获取当前设备信息
   * @return 设备运行状态等信息
   */
  void GetDeviceInfo( ::SampleReg::DeviceInfo& _return) override;
  void send_GetDeviceInfo();
  void recv_GetDeviceInfo( ::SampleReg::DeviceInfo& _return);
  /**
   * 获取当前通用操作信息
   * @return 通用操作的执行状态及结果
   */
  void GetOperInfo( ::SampleReg::GeneralOperInfo& _return) override;
  void send_GetOperInfo();
  void recv_GetOperInfo( ::SampleReg::GeneralOperInfo& _return);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class SampleRegLCProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<SampleRegLCIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (SampleRegLCProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_HeartbeatToLC(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_DistributeOper(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_DistributeTask(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_GetTaskInfo(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_GetDeviceInfo(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_GetOperInfo(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  SampleRegLCProcessor(::std::shared_ptr<SampleRegLCIf> iface) :
    iface_(iface) {
    processMap_["HeartbeatToLC"] = &SampleRegLCProcessor::process_HeartbeatToLC;
    processMap_["DistributeOper"] = &SampleRegLCProcessor::process_DistributeOper;
    processMap_["DistributeTask"] = &SampleRegLCProcessor::process_DistributeTask;
    processMap_["GetTaskInfo"] = &SampleRegLCProcessor::process_GetTaskInfo;
    processMap_["GetDeviceInfo"] = &SampleRegLCProcessor::process_GetDeviceInfo;
    processMap_["GetOperInfo"] = &SampleRegLCProcessor::process_GetOperInfo;
  }

  virtual ~SampleRegLCProcessor() {}
};

class SampleRegLCProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  SampleRegLCProcessorFactory(const ::std::shared_ptr< SampleRegLCIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< SampleRegLCIfFactory > handlerFactory_;
};

class SampleRegLCMultiface : virtual public SampleRegLCIf {
 public:
  SampleRegLCMultiface(std::vector<std::shared_ptr<SampleRegLCIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~SampleRegLCMultiface() {}
 protected:
  std::vector<std::shared_ptr<SampleRegLCIf> > ifaces_;
  SampleRegLCMultiface() {}
  void add(::std::shared_ptr<SampleRegLCIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  /**
   * 向上位机发送心跳
   * @param timeStamp 时间戳（毫秒级）
   * 
   * @param timeStamp
   */
  void HeartbeatToLC(const int64_t timeStamp) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->HeartbeatToLC(timeStamp);
    }
    ifaces_[i]->HeartbeatToLC(timeStamp);
  }

  /**
   * 发布通用操作指令
   * @param info 通用操作信息（包含指令及参数）
   * @return 0表示下发成功，非0表示错误码
   * 
   * @param info
   */
  int32_t DistributeOper(const  ::SampleReg::GeneralOperInfo& info) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->DistributeOper(info);
    }
    return ifaces_[i]->DistributeOper(info);
  }

  /**
   * 发布任务指令
   * @param info 任务信息（包含任务ID、类型等）
   * @return 0表示下发成功，非0表示错误码
   * 
   * @param info
   */
  int32_t DistributeTask(const  ::SampleReg::TaskInfo& info) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->DistributeTask(info);
    }
    return ifaces_[i]->DistributeTask(info);
  }

  /**
   * 获取当前任务信息
   * @return 任务详细信息
   */
  void GetTaskInfo( ::SampleReg::TaskInfo& _return) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->GetTaskInfo(_return);
    }
    ifaces_[i]->GetTaskInfo(_return);
    return;
  }

  /**
   * 获取当前设备信息
   * @return 设备运行状态等信息
   */
  void GetDeviceInfo( ::SampleReg::DeviceInfo& _return) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->GetDeviceInfo(_return);
    }
    ifaces_[i]->GetDeviceInfo(_return);
    return;
  }

  /**
   * 获取当前通用操作信息
   * @return 通用操作的执行状态及结果
   */
  void GetOperInfo( ::SampleReg::GeneralOperInfo& _return) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->GetOperInfo(_return);
    }
    ifaces_[i]->GetOperInfo(_return);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class SampleRegLCConcurrentClient : virtual public SampleRegLCIf {
 public:
  SampleRegLCConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  SampleRegLCConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  /**
   * 向上位机发送心跳
   * @param timeStamp 时间戳（毫秒级）
   * 
   * @param timeStamp
   */
  void HeartbeatToLC(const int64_t timeStamp) override;
  int32_t send_HeartbeatToLC(const int64_t timeStamp);
  void recv_HeartbeatToLC(const int32_t seqid);
  /**
   * 发布通用操作指令
   * @param info 通用操作信息（包含指令及参数）
   * @return 0表示下发成功，非0表示错误码
   * 
   * @param info
   */
  int32_t DistributeOper(const  ::SampleReg::GeneralOperInfo& info) override;
  int32_t send_DistributeOper(const  ::SampleReg::GeneralOperInfo& info);
  int32_t recv_DistributeOper(const int32_t seqid);
  /**
   * 发布任务指令
   * @param info 任务信息（包含任务ID、类型等）
   * @return 0表示下发成功，非0表示错误码
   * 
   * @param info
   */
  int32_t DistributeTask(const  ::SampleReg::TaskInfo& info) override;
  int32_t send_DistributeTask(const  ::SampleReg::TaskInfo& info);
  int32_t recv_DistributeTask(const int32_t seqid);
  /**
   * 获取当前任务信息
   * @return 任务详细信息
   */
  void GetTaskInfo( ::SampleReg::TaskInfo& _return) override;
  int32_t send_GetTaskInfo();
  void recv_GetTaskInfo( ::SampleReg::TaskInfo& _return, const int32_t seqid);
  /**
   * 获取当前设备信息
   * @return 设备运行状态等信息
   */
  void GetDeviceInfo( ::SampleReg::DeviceInfo& _return) override;
  int32_t send_GetDeviceInfo();
  void recv_GetDeviceInfo( ::SampleReg::DeviceInfo& _return, const int32_t seqid);
  /**
   * 获取当前通用操作信息
   * @return 通用操作的执行状态及结果
   */
  void GetOperInfo( ::SampleReg::GeneralOperInfo& _return) override;
  int32_t send_GetOperInfo();
  void recv_GetOperInfo( ::SampleReg::GeneralOperInfo& _return, const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
